Ref = 'AATTGCTA'
seq1 = 'AATT'
seq2 = 'TAGC'

seq2reverse = seq2[len(Ref)-len(seq1)-1::-1]
complement = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}

final = seq1 + ''.join(complement.get(base, base) for base in seq2reverse)
print('Your protein sequence is:', final)

if Ref != final:
    print('There is a mismatch')
else:
    print('There is no mismatch')

if 'N' in Ref+seq1+seq2:
    print("One of the sequences has an 'N'")

    
    
    ##from mega
ref =  '-------------------------------------------------GTCGACTACAGTCCAATGGTGGTGC-CAC-----AGAAGAACGTACCC-CTGCCAATCGACGACAA-GTCGTCAT-CG-A-TGGA-GT--TGCCTCAGATAC-A-CGCGGA-T-A-C--GATTGG-TCG----GTTGGTCTT-AGA-AA-AGTTCA-TGGA-A-G-TAA--------TCAAG-------GGCCAGGAGGCTTACTCGCGTCGAAAGGTATTAGCGGGCATTGTAATGACTGAAAACATGAATTTTTGTGAAGCCAAAGTTATTTCAGTTTCGACGGGCACCAAGTGTGTCAGCGGTGAGCATATGAGTGTGAACGGAGCTGTCCTAAATGATTCCCATGCTGAAATAGTCTCCAGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGACCTTCAGTGCAATCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAAGGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGCCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCCAAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGCCAGGTGTCTCGCATCACAAAGCAGGCGTTTTTCGTTAAGTATGGATTTCTAATGGCAAACTTGCCCGGTATTTTAGTCCGCAA------AG------------------TAACC--AC---TGACTATGGG--CAAA-----CCA---AAGCTAACG---TTAAGG--ACTA---TC--AGAT-C---GCAAAGCT----AGAA-TTGTTC--TCTGCAT-T-CAAGCGAGAAG--ACCTTGGCAGCTG--G------CT---GAAGAA-ACCCATT-GAAC----AAGAC-G-AGTT-C-GGTCTTGCCGAATGAGCG---GCCGC---'
seq1 = 'CNNNNNNNNNNNNNNNNNNNGNNANCGTTACGTATCGGNTCNNNNNNTCGTCGACTNCNGTCNNATGGTGGTGC-CAC-----AGAAGAACGTACCC-CTGCCAATCGACGACAA-GTCGTCAT-CG-A-TGGA-GT--TGCCTCAGATAC-A-CGCGGA-T-A-C--GATTGG-TCG----GTTGGTCTT-AGA-AA-AGTTCA-TGGA-A-G-TAA--------TCAAG-------GGCCAGGAGGCTTACTCGCGTCGAAAGGTATTAGCGGGCATTGTAATGACTGAAAACATGAATTTTTGTGAAGCCAAAGTTATTTCAGTTTCGACGGGCACCAAGTGTGTCAGCGGTGAGCATATGAGTGTGAACGGAGCTGTCCTAAATGATTCCCATGCTGAAATAGTCTCCAGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGACCTTCAGTGCAATCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAANGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGNCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCNNAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGNNAGGTGTCTCGCATCACAAAGCNN-CGTTTTTCGTTTANTATGGNTTTCTAATGGCAAACTTGCCNNNN-TTTTAGTCCGNAAGTAACCNNCTGACTATNGGNNAAACCNAANCTAACGTTNNNCTATNNGATCNNNAAGCNNNAATTNNNNNNNNGCNTTNAAGNCNNNNAGACNNGNAGNTGNTGANNAANNNNTTNANNANANNNTNCGGNNTNCNNATGNNNNNNNNNNNTTNNNNNNNNNNCNN--NA-----NNC-CNNNNANTNNNNNNN-NNNNTTT-NNNNN-N-NNNN-CTNNNNNNNNNNNANNANNNCTNNNCNNNNN'
seq2 = 'NNNNNGNNNNNNATNNNCNNNNNNTNNNNNCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNGNNNCGNTTNNNNNNNNGNANNCANNNTNNNTNGANNNNANTNNNNNNNNGNNCNCNNNAANNAANGNNNCNNNNNNTNGNNNNNAGTCNTNATNNNNGNGTNGCTCANNTNNNNNNGNNACNATNGNTNNGTNNNTNTNANAAAAGTTCATNNAAGTANTCAANGNNNNNNGGNTTACNNGNNTCGAAAGGTNNTAGCGGGCATTGTAANGACTNAAAACATNAATTTTNNNGAAGCNAAAGTTATTTCAGTTTCGACGGGCACCAAGTGNNNCAGCGNTGAGCATATGAGTGTGAACGGAGCTGNNN-AAATGATTCCCATGCTGAAATAGTNNC-AGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGAC-TTCAGTGCANTCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAAGGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGCCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCCAAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGCCAGGTGTCTCGCATCACAAAGCAGGCGTTTTTCGTTAAGTATGGATTTCTAATGGCAAACTTGCCCGGTATTTTAGTCCGCAA------AG------------------TAACC--AC---TGACTATGGG--CAAA-----CCA---AAGCTAACG---TTAAGG--ACTA---TC--AGAT-C---GCAAAGCT----AGAA-TTGTTC--TCTGCAT-T-CAAGCGAGAAG--ACCTTGGCAGCNGCTGAAGAAACCCATNAACAAGACGAGTTCGGTCTTNCNNAANAGCGGCCGC-NGTNTNNNNGNNNNNNNN--NNNNNNNNN'
final = ''
a = 0
for index, value in enumerate(ref):
    if value == '-':
        pass
    elif value == seq1[index] or value == seq2[index]:
        final = final + value
    elif value != seq1[index] and value != seq2[index]:
        a += 1
        final = final + value.lower()
    else:
        print('The position is {}, the ref base is {}, the alternate is {} or {}'.format(index, value, seq1[index], seq2[index]))
print(final)
