Ref = 'AATTGCTA'
seq1 = 'AATT'
seq2 = 'TAGC'

seq2reverse = seq2[len(Ref)-len(seq1)-1::-1]
complement = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}

final = seq1 + ''.join(complement.get(base, base) for base in seq2reverse)
print('Your protein sequence is:', final)

if Ref != final:
    print('There is a mismatch')
else:
    print('There is no mismatch')

if 'N' in Ref+seq1+seq2:
    print("One of the sequences has an 'N'")

    
    
    ##from mega
ref =  '-------------------------------------------------GTCGACTACAGTCCAATGGTGGTGC-CAC-----AGAAGAACGTACCC-CTGCCAATCGACGACAA-GTCGTCAT-CG-A-TGGA-GT--TGCCTCAGATAC-A-CGCGGA-T-A-C--GATTGG-TCG----GTTGGTCTT-AGA-AA-AGTTCA-TGGA-A-G-TAA--------TCAAG-------GGCCAGGAGGCTTACTCGCGTCGAAAGGTATTAGCGGGCATTGTAATGACTGAAAACATGAATTTTTGTGAAGCCAAAGTTATTTCAGTTTCGACGGGCACCAAGTGTGTCAGCGGTGAGCATATGAGTGTGAACGGAGCTGTCCTAAATGATTCCCATGCTGAAATAGTCTCCAGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGACCTTCAGTGCAATCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAAGGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGCCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCCAAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGCCAGGTGTCTCGCATCACAAAGCAGGCGTTTTTCGTTAAGTATGGATTTCTAATGGCAAACTTGCCCGGTATTTTAGTCCGCAA------AG------------------TAACC--AC---TGACTATGGG--CAAA-----CCA---AAGCTAACG---TTAAGG--ACTA---TC--AGAT-C---GCAAAGCT----AGAA-TTGTTC--TCTGCAT-T-CAAGCGAGAAG--ACCTTGGCAGCTG--G------CT---GAAGAA-ACCCATT-GAAC----AAGAC-G-AGTT-C-GGTCTTGCCGAATGAGCG---GCCGC---'
seq1 = 'CNNNNNNNNNNNNNNNNNNNGNNANCGTTACGTATCGGNTCNNNNNNTCGTCGACTNCNGTCNNATGGTGGTGC-CAC-----AGAAGAACGTACCC-CTGCCAATCGACGACAA-GTCGTCAT-CG-A-TGGA-GT--TGCCTCAGATAC-A-CGCGGA-T-A-C--GATTGG-TCG----GTTGGTCTT-AGA-AA-AGTTCA-TGGA-A-G-TAA--------TCAAG-------GGCCAGGAGGCTTACTCGCGTCGAAAGGTATTAGCGGGCATTGTAATGACTGAAAACATGAATTTTTGTGAAGCCAAAGTTATTTCAGTTTCGACGGGCACCAAGTGTGTCAGCGGTGAGCATATGAGTGTGAACGGAGCTGTCCTAAATGATTCCCATGCTGAAATAGTCTCCAGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGACCTTCAGTGCAATCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAANGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGNCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCNNAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGNNAGGTGTCTCGCATCACAAAGCNN-CGTTTTTCGTTTANTATGGNTTTCTAATGGCAAACTTGCCNNNN-TTTTAGTCCGNAAGTAACCNNCTGACTATNGGNNAAACCNAANCTAACGTTNNNCTATNNGATCNNNAAGCNNNAATTNNNNNNNNGCNTTNAAGNCNNNNAGACNNGNAGNTGNTGANNAANNNNTTNANNANANNNTNCGGNNTNCNNATGNNNNNNNNNNNTTNNNNNNNNNNCNN--NA-----NNC-CNNNNANTNNNNNNN-NNNNTTT-NNNNN-N-NNNN-CTNNNNNNNNNNNANNANNNCTNNNCNNNNN'
seq2 = 'NNNNNGNNNNNNATNNNCNNNNNNTNNNNNCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNGNNNCGNTTNNNNNNNNGNANNCANNNTNNNTNGANNNNANTNNNNNNNNGNNCNCNNNAANNAANGNNNCNNNNNNTNGNNNNNAGTCNTNATNNNNGNGTNGCTCANNTNNNNNNGNNACNATNGNTNNGTNNNTNTNANAAAAGTTCATNNAAGTANTCAANGNNNNNNGGNTTACNNGNNTCGAAAGGTNNTAGCGGGCATTGTAANGACTNAAAACATNAATTTTNNNGAAGCNAAAGTTATTTCAGTTTCGACGGGCACCAAGTGNNNCAGCGNTGAGCATATGAGTGTGAACGGAGCTGNNN-AAATGATTCCCATGCTGAAATAGTNNC-AGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGAC-TTCAGTGCANTCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAAGGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGCCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCCAAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGCCAGGTGTCTCGCATCACAAAGCAGGCGTTTTTCGTTAAGTATGGATTTCTAATGGCAAACTTGCCCGGTATTTTAGTCCGCAA------AG------------------TAACC--AC---TGACTATGGG--CAAA-----CCA---AAGCTAACG---TTAAGG--ACTA---TC--AGAT-C---GCAAAGCT----AGAA-TTGTTC--TCTGCAT-T-CAAGCGAGAAG--ACCTTGGCAGCNGCTGAAGAAACCCATNAACAAGACGAGTTCGGTCTTNCNNAANAGCGGCCGC-NGTNTNNNNGNNNNNNNN--NNNNNNNNN'
final = ''
a = 0
for index, value in enumerate(ref):
    if value == '-':
        pass
    elif value == seq1[index] or value == seq2[index]:
        final = final + value
    elif value != seq1[index] and value != seq2[index]:
        a += 1
        final = final + value.lower()
    else:
        print('The position is {}, the ref base is {}, the alternate is {} or {}'.format(index, value, seq1[index], seq2[index]))
print(final)



#To check for which positions do what
#Paste your reference, primer1 sequence, primer2 sequence in each of these variables within the quotation marks
with open('that.csv') as f:
    lines = f.read().splitlines()
ref = lines[0]
seq1 = lines[1]
seq2 = lines[2]
final = ''
a = 0
b = 0
g = []
for index, value in enumerate(ref):
    if value == '-':
        pass
    elif value == seq1[index] or value == seq2[index]:
        final = final + value
        b = b+1
    elif seq1[index] not in 'ATGC' and seq2[index] not in ['ATGC']:
        a = a+1
        print(index, 'ref = ' + ref[index::], '\n', 'seq 1 = ' + seq1[index::], '\n', 'seq 2 = ' + seq2[index::], '\n')
        final = final + value.lower()
    # else
    #     print('The position is {}, the ref base is {}, the alternate is {} or {}'.format(index, value, seq1[index], seq2[index]))
print('\n'.join(g))
print(a, b, len(final), a+b)

#that.csv
-------------------------------------------------GTCGACTACAGTCCAATGGTGGTGCCACAGAAGAACGTACCCCTGCCAATCGACGACAAGTCGTCATCGATGGAGTTGCCTCAGATACACGCGGATACGATTGGTCGGTTGGTCTTAGAAAAGTTCATGGAAGTAATCAAGGGCCAGGAGGCTTACTCGCGTCGAAAGGTATTAGCGGGCATTGTAATGACTGAAAACATGAATTTTTGTGAAGCCAAAGTTATTTCAGTTTCGACGGGCACCAAGTGTGTCAGCGGTGAGCATATGAGTGTGAACGGAGCTGTCCTAAATGATTCCCATGCTGAAATAGTCTCCAGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGACCTTCAGTGCAATCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAAGGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGCCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCCAAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGCCAGGTGTCTCGCATCACAAAGCAGGCGTTTTTCGTTAAGTATGGATTTCTAATGGCAAACTTGCCCGGTATTTTAGTCCGCAAAGTAACCACTGACTATGGGCAAACCAAAGCTAACGTTAAGGACTATCAGATCGCAAAGCTAGAATTGTTCTCTGCATTCAAGCGAGAAGACCTTGGCAGCTGGCTGAAGAAACCCATTGAACAAGACGAGTTCGGTCTTGCCGAATGAGCGGCCGC------------
CNNNNNNNNNNNNNNNNNNNGNNANCGTTACGTATCGGNTCNNNNNNTCGTCGACTNCNGTCNNATGGTGGTGCCACAGAAGAACGTACCCCTGCCAATCGACGACAAGTCGTCATCGATGGAGTTGCCTCAGATACACGCGGATACGATTGGTCGGTTGGTCTTAGAAAAGTTCATGGAAGTAATCAAGGGCCAGGAGGCTTACTCGCGTCGAAAGGTATTAGCGGGCATTGTAATGACTGAAAACATGAATTTTTGTGAAGCCAAAGTTATTTCAGTTTCGACGGGCACCAAGTGTGTCAGCGGTGAGCATATGAGTGTGAACGGAGCTGTCCTAAATGATTCCCATGCTGAAATAGTCTCCAGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGACCTTCAGTGCAATCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAAGGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGCCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCCAAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGCCAGGTGTCTCGCATCACAAAGCAGGCGTTTTTCGTTAAGTATGGATTTCTAATGGCAAACTTGCCCGGTATTTTAGTCCGCAAAGTAACCACTGACTATGGGCAAACCAAAGCTAACGTTAAGGACTATCAGATCGCAAAGCTAGAATTGTTCTCTGCATTCAAGCGAGAAGACCTTGGCAGCNG-CTGAAGAAACCCATN-AACAAGACGAGTTCGGTCTTNCNNAAN-AGCGGCCGCNGTNTNNNNGNNNNNNNNNNNNNNNNN
CNNNNNNNNNNNNNNNNNNNGNNANCGTTACGTATCGGNTCNNNNNNTCGTCGACTNCNGTCNNATGGTGGTGCCACAGAAGAACGTACCCCTGCCAATCGACGACAAGTCGTCATCGATGGAGTTGCCTCAGATACACGCGGATACGATTGGTCGGTTGGTCTTAGAAAAGTTCATGGAAGTAATCAAGGGCCAGGAGGCTTACTCGCGTCGAAAGGTATTAGCGGGCATTGTAATGACTGAAAACATGAATTTTTGTGAAGCCAAAGTTATTTCAGTTTCGACGGGCACCAAGTGTGTCAGCGGTGAGCATATGAGTGTGAACGGAGCTGTCCTAAATGATTCCCATGCTGAAATAGTCTCCAGGCGTTGTCTTCTCAAATATTTATATGCACAGCTGGACCTTCAGTGCAATCAGGCCACAGCATATCAGTCGATTTTCGTGAGGAATACTGATGGGCAATACCCTTATAAACTAAAATCCGGGGTACATTTCCATTTGTATATAAATACAGCACCTTGTGGGGATGCACGGATATTTAGTCCTCACGAAAACGACACTGGTGTTGATAAACATCCAAATAGAAAAGCTCGTGGCCAGCTGCGCACCAAAATCGAGTCCGGTGAGGGGACGATTCCAGTGAAAAGCAGTGATGGTATCCAGACGTGGGATGGCGTATTGCAGGGCCAACGCCTGCTAACAATGTCGTGCTCGGATAAAATTGCCCGTTGGAACATCGTGGGCATCCAAGGCTCACTATTGTCTTCCATAATTGAACCGGTGTACCTGCATTCGATTGTGCTGGGAAGCCTGTTGCATCCGGAGCACATGTACCGCGCAGTTTGCGGCCGAATTGAGAAGTCCATTCAAGGCCTGCCACCGCCGTACCATCTGAACAAGCCGCGCCTGGCACTAGTCACTTCGGCCGAGCCGCGGAATCAGGCCAAGGCTCCCAACTTCGGGATCAATTGGACCATTGGGGACACCGAGCTGGAAGTGGTGAACTCGCTAACCGGTCGAACCATTGGCGGCCAGGTGTCTCGCATCACAAAGCAGGCGTTTTTCGTTAAGTATGGATTTCTAATGGCAAACTTGCCCGGTATTTTAGTCCGCAAAGTAACCACTGACTATGGGCAAACCAAAGCTAACGTTAAGGACTATCAGATCGCAAAGCTAGAATTGTTCTCTGCATTCAAGCGAGAAGACCTTGGCAGCNG-CTGAAGAAACCCATN-AACAAGACGAGTTCGGTCTTNCNNAAN-AGCGGCCGCNGTNTNNNNGNNNNNNNNNNNNNNNNN
